name: C/C++ CI on CentOS 7

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # 使用 CentOS 7 环境
    runs-on: ubuntu-latest  # GitHub 没有直接的 CentOS 7 运行器，我们需要使用容器
    
    container:
      image: centos:7
      options: --cpus 1

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install development tools
      run: |
        yum -y update
        yum -y install make gcc-c++ which
        
    - name: Build project
      run: make
      
    - name: List all files after build
      run: ls -la
      
    - name: Check if server executable exists
      run: |
        if [ -f "server" ]; then
          echo "✅ Server executable found"
          ls -la server
          chmod +x server
        else
          echo "❌ Server executable not found"
          echo "Current directory contents:"
          ls -la
          echo "Looking for any executable files:"
          find . -type f -executable -name "*" | head -20
          exit 1
        fi
        
    - name: Test the server executable
      run: |
        # 尝试运行服务器
        timeout 5s ./server --version || ./server -v || echo "Version check not available"
        echo "Server test completed"
        
    - name: Check library dependencies
      run: |
        echo "Checking library dependencies:"
        ldd server || echo "ldd command may not be available"
        
    - name: Create package directory
      run: |
        mkdir -p package
        cp server package/
        # 复制可能的配置文件或其他必要文件
        cp -r config/ package/ 2>/dev/null || true
        cp -r app/ package/ 2>/dev/null || true
        cp -r web/ package/ 2>/dev/null || true
        echo "Package contents:"
        find package/ -type f
        
    - name: Create compressed package
      run: |
        tar -czf ${{ github.event.repository.name }}-${{ github.sha }}.tar.gz package/
        ls -la *.tar.gz
        
    - name: Upload server executable
      uses: actions/upload-artifact@v4
      with:
        name: server-executable-centos7
        path: server
        if-no-files-found: error
        
    - name: Upload complete package
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-centos7-package
        path: ${{ github.event.repository.name }}-${{ github.sha }}.tar.gz
        if-no-files-found: error
